/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface CloudflareEnv ./cloudflare-env.d.ts` (hash: 6d50a85347cc0ecfbecbcda94a1e6a40)
declare namespace Cloudflare {
	interface Env {
		NEXTJS_ENV: string;
		SESSION_SEAL_SECRET: string;
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		WORKER_SELF_REFERENCE: Fetcher /* nouners */;
		ASSETS: Fetcher;
	}
}
interface CloudflareEnv extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXTJS_ENV" | "SESSION_SEAL_SECRET">> {}
}
